"""fix grillsessiondata relationship

Revision ID: 3a176dbb444e
Revises: 7a42589f1100
Create Date: 2019-02-28 23:00:57.084386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a176dbb444e'
down_revision = '7a42589f1100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
