"""change table names to avoid reserved name conflicts

Revision ID: 7a42589f1100
Revises: f8ef93523b39
Create Date: 2019-02-28 22:53:03.820622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a42589f1100'
down_revision = 'f8ef93523b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
