"""add SessionData table

Revision ID: f8ef93523b39
Revises: 9b01896e5dc1
Create Date: 2019-02-28 22:44:42.268127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ef93523b39'
down_revision = '9b01896e5dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('setpoint', sa.Integer(), nullable=True),
    sa.Column('fan', sa.Integer(), nullable=True),
    sa.Column('temp0', sa.Integer(), nullable=True),
    sa.Column('temp1', sa.Integer(), nullable=True),
    sa.Column('temp2', sa.Integer(), nullable=True),
    sa.Column('temp3', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_data')
    # ### end Alembic commands ###
